### ISSUE TITLE
Filtering is not working with converters

### ISSUE THREAD

**Issue by KeoSoft** [dotnet/DataGridExtensions#102]
if you set a converter on a DataGridTextColumn the filtering is not using the converted value, instead it will search using the binding property, if you use a converter to get the username for example from an int ID property, the search filter will ignore the converter so that if you type "john" for example it will search for "john" in a set of int values and no result return

**Comment by tom-englert** [comment]
I think that's by design, the `SearchMemberPath` is the only common thing among all column types, and the built in search woks the same way - it would be confusing if search and filtering would get different results.

**Comment by KeoSoft** [comment]
What if we could access information about column binding, then we can use the converter to return the actual value ?

**Comment by tom-englert** [comment]
Does sorting the column work correctly on such a column with a converter?

**Comment by tom-englert** [comment]
Sorting does not work with a converter either, it sorts by the index, not by the string displayed:

![BasicSample_fu49fSpDlf](https://github.com/dotnet/DataGridExtensions/assets/10229954/287d1dc6-14d7-4a59-8ec0-5af69bab015f)

Now that proves that changing the behavior would introduce inconsistencies.

You need to provide a property in your items model that returns the name from the ID, instead of looking up the name in a converter.

**Comment by KeoSoft** [comment]
I ended up using the [NotMapped] attribute to add extra properties to the entity using partial classes. I hope that the DataGrid sorting behavior will change in the future.

**Comment by tom-englert** [comment]
> I ended up using the [NotMapped] attribute to add extra properties to the entity using partial classes.
Using entities as view models is an anti-pattern, you should strictly avoid this
> I hope that the DataGrid sorting behavior will change in the future.
I don't think so, there is no more active feature development on WPF
