### ISSUE TITLE
Filtering multiple columns, previous filters will fail

### ISSUE THREAD

**Issue by BigBirdBoom** [dotnet/DataGridExtensions#67]
Hello
Something strange happened when I ran the sample (DataGridExtensionsSample) you provided.
Here are the steps I took.

Step 1 : Reset all filters on this page.

![Step1](https://user-images.githubusercontent.com/36618083/122940968-863bd780-d3a7-11eb-8b04-d686cf818715.png)

Step 2 : Uncheck the second and fourth items in the fifth column

![Step2](https://user-images.githubusercontent.com/36618083/122946438-f0567b80-d3ab-11eb-8624-6554195c4305.png)

Step 3 : Check the "i" and "p" in the ninth column

![Step3](https://user-images.githubusercontent.com/36618083/122946662-23990a80-d3ac-11eb-8775-07968d6a093e.png)

Step 4 : Uncheck "3" in the eighth column

![Step4](https://user-images.githubusercontent.com/36618083/122946892-52af7c00-d3ac-11eb-900f-958914c72c06.png)

After that, the previously filtered columns become unfiltered.
Thank you!

**Comment by shengjhen** [comment]
I have similar issue with that.
1.Filtered all column at current screen.-->OK.
2.Try sort each column at current screen.-->OK.
3.Scroll the Horizontal Scroller to right until first column can't see.
4.Sorting new column would cause filter failed.-->Fail.

**Comment by tom-englert** [comment]
@BigBirdBoom maybe that's because most of the grid columns are showing/filtering the same data columns with conflicting filters?
@shengjhen that I can't reproduce

**Comment by shengjhen** [comment]
> @BigBirdBoom maybe that's because most of the grid columns are showing/filtering the same data columns with conflicting filters?
> @shengjhen that I can't reproduce
Sorry,please accept my apologies,the problem came from my project,not from example.
DataGrid's property like below
1.Testing is ok for everything
VirtualizingPanel.IsVirtualizing="True" VirtualizingPanela.ScrollUnit="Pixel" VirtualizingPanel.IsVirtualizingWhenGrouping="True" VirtualizingPanel.IsContainerVirtualizable="True" VirtualizingPanel.CacheLengthUnit="Pixel" VirtualizingPanel.VirtualizationMode="Recycling"  EnableRowVirtualization="True" **EnableColumnVirtualization="False"**
2.filter will be failed when the filtered columns are invisible and click visible column to sort.
VirtualizingPanel.IsVirtualizing="True" VirtualizingPanela.ScrollUnit="Pixel" VirtualizingPanel.IsVirtualizingWhenGrouping="True" VirtualizingPanel.IsContainerVirtualizable="True" VirtualizingPanel.CacheLengthUnit="Pixel" VirtualizingPanel.VirtualizationMode="Recycling"  EnableRowVirtualization="True" **EnableColumnVirtualization="True"**

**Comment by tom-englert** [comment]
@shengjhen That should have been fixed already here: #23. 
Are you using the latest version? 
If yes, can you provide a repo sample, preferably as a PR for the sample application

**Comment by shengjhen** [comment]
> @shengjhen That should have been fixed already here: #23.
> Are you using the latest version?
> If yes, can you provide a repo sample, preferably as a PR for the sample application

Yes.I use the latest version.
![image](https://user-images.githubusercontent.com/42288446/127723374-5672b9e0-372c-47ce-bbaf-0c6771beec2a.png)
Same issue when i try use the sample which provide from this repo.
<img width="563" alt="UlI2zpvC9V" src="https://user-images.githubusercontent.com/42288446/127723219-c996a146-8c61-4f47-85fe-0b5fd6d23a43.png">
![image](https://user-images.githubusercontent.com/42288446/127723193-28556f65-5973-4fb8-93e3-ebe91bd85551.png)

**Comment by tom-englert** [comment]
OK, now I found it. Since this seems to be something different than the original issue, I moved this to #68

**Comment by tom-englert** [comment]
Looks like the fix for #68 also fixed this.
